version: "3"
services:
  web:
    build: ./web
    ports:
      - "8000:8000"
    volumes:
      - ./web/app:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    env_file: .env
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=open_cv